# Generated by Django 4.2.6 on 2023-10-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('book_title', models.CharField(max_length=200)),
                ('book_subtitle', models.CharField(max_length=200)),
                ('book_authors', models.CharField(max_length=200)),
                ('book_publisher', models.CharField(max_length=100)),
                ('book_publishdate', models.DateField()),
                ('book_category', models.CharField(max_length=100)),
                ('book_distexpense', models.FloatField()),
            ],
        ),
    ]
