# Generated by Django 4.2.6 on 2023-10-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField()),
                ('desc', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
